#+hugo_base_dir: .
#+hugo_section: post
#+hugo_auto_set_lastmod: t
* Posts
** Creating Hugo Posts with Emacs, Org Mode and Ox-Hugo :Hugo:Blogging:Org:Mode:Emacs:CI:CD:
#+DATE: 2021-05-11
Will be based on =ox-hugo= and use Org-mode /properties/ and specific properties
for =ox-hugo=
- https://ox-hugo.scripter.co/doc/dates/
*** TODO Installing Hugo
*** TODO Creating the project
*** TODO Setting the template
*** TODO Export to Hugo md-files
*** TODO Auto depoly new changes from Github to you site
Hugo and Netlify change the build configuration and settings from time to time.
I noticed that one day by continous deployment with Netlify stopped working. To fix this I followed [[https://maraaverick.rbind.io/2017/10/updating-blogdown-hugo-version-netlify/][This Guide]] and set the =HUGO_VERSION= to =0.73.0=
*** TODO *(Optional) Set a domain name
** About Programming
Harping on any one programming paradime is counter productive. Object-Oriented
Programming may be the most popular programming style for a wide set of
programming languages - I think it's safe to say that most newer languages, such
as Go, Rust etc, are moving away from that approach. I think languages should be
pragmatic and solution focused and not enforce a programmatic ideology for how
you should think about and structure your code. However, I do enforce
standardization and global standards for formatting for readability and structure. And for me, it mostly comes down to the core essence of what coding to me is about:

1. Solving you problem 
2. Expressing your intent with your solution 
3. Making it readable and with clear intent. 
4. Isolation of concerns
5. Solving it well

Your code will be read about 80/90% of the time, and writing it about 10/20% of the time. having you code read well and being subject to change is therefore essential. No one project starts out with a clear instruction and goal in mind. Tasks, aims and descriptions change and evolve over time as you or your customers get a better understanding of what it is you truly want and can realistically do.

- Martin Fowler and Kent Beck's TTD (not unit tests)
- Data-Oriented Programming
- Leave the code in the same state as your kitchen - Clean
- Do not take time out to refactor your code. Always do it as you work!
